#!/bin/bash

# Check if the commit message follows the conventional commit: "<verb>(optional_scope): descriptive message"
if ! grep -qE '^(feat|fix|docs|style|refactor|test|chore)(\([a-z-]+\))?[:] .+' <<< "$1"; then
  echo "Commit message does not follow conventional commit convention"
  exit 1
fi