#!/bin/bash

# Check if PHPStan && PHP AT are installed
if [ -f vendor/bin/phpstan ]; then
  vendor/bin/phpstan analyse src --quiet || {
    echo "PHPStan analysis failed, commit aborted."
    exit 1
  }
else
  echo "PHPStan is not installed, commit aborted."
  exit 1
fi

