#!/bin/bash

# Get a list of all files that will be committed
files=$(git diff-index --cached --name-only HEAD)

# Check for missing declare(strict_types=1) in /src
if grep -rl --exclude-dir=vendor --exclude=composer.json '^<\?php\s*class\s' src | xargs grep -L 'declare\(strict_types=1\)'; then
  echo "Found PHP class without declare(strict_types=1) in src/"
  exit 1
fi