#!/bin/bash

# Check if PHPStan && PHP AT are installed
if [ -f vendor/bin/phpunit ]; then
  vendor/bin/phpunit || {
    echo "PHPUnit tests failed, commit aborted."
    exit 1
  }
else
  echo "PHPUnit is not installed, commit aborted."
  exit 1
fi
